lib/task2_web/router.ex
defmodule Task2Web.Router do
  use Task2Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug Task2.Plugs.GetCurrentUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Task2Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController do
      get "/complete", TaskController, :complete, as: :complete
    end
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", Task2Web do
    pipe_through :api
    resources "/timeblocks", TimeblockController, except: [:new, :edit]
  end
end

lib/task2/social/task.ex
defmodule Task2.Social.Task do
  use Ecto.Schema
  import Ecto.Changeset
  alias Task2.Social.Task


  schema "tasks" do
    field :body, :string
    field :time, :integer
    field :title, :string
    belongs_to :creater, Task2.Accounts.User
    belongs_to :user, Task2.Accounts.User
    has_many :timeblocks ,Task2.Social.Timeblock, foreign_key: :task_id 

    timestamps()
  end

  @doc false
  def changeset(%Task{} = task, attrs) do
    task
    |> cast(attrs, [:title, :body, :user_id, :creater_id, :time])
    |> foreign_key_constraint(:user_id)
    |> foreign_key_constraint(:creater_id)
    |> validate_required([:title, :body, :creater_id, :user_id])
  end
end

lib/task2_web/controllers/task_controller.ex
defmodule Task2Web.TaskController do
  use Task2Web, :controller

  alias Task2.Social
  alias Task2.Social.Task
  alias Task2.Accounts

  def index(conn, _params) do
    tasks = Social.list_tasks()
    render(conn, "index.html", tasks: tasks)
  end

  def new(conn, params) do
    user_id_list = Accounts.get_all_id(conn.assigns.current_user.id)
    if (length(user_id_list)) == 0 do
      conn
      |> put_flash(:error, "You are not a manager.")
      |> redirect(to: task_path(conn, :index))
    else
      changeset = Social.change_task(%Task{})
      render(conn, "new.html", changeset: changeset, task: %Task{}, user_id_list: user_id_list)
    end

  end


  def create(conn, %{"task" => task_params}) do
    case Social.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, task: %Task{})
    end
  end

  def show(conn, %{"id" => id}) do
    task = Social.get_task!(id)
    render(conn, "show.html", task: task)
  end

  def edit(conn, %{"id" => id}) do
    user_id_list = Accounts.get_all_id(conn.assigns.current_user.id)
    task = Social.get_task!(id)
    changeset = Social.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset, user_id_list: user_id_list)
  end


  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Social.get_task!(id)
    case Social.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: task_path(conn, :show, task))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Social.get_task!(id)
    {:ok, _task} = Social.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: task_path(conn, :index))
  end

  def complete(conn, %{"task_id" => id}) do
    task = Social.get_task!(id)
    time = List.foldr(task.timeblocks, 0, fn(x, acc) -> diff_time(x) + acc end)
    changeset = Social.change_task(task)
    render(conn, "complete.html", task: task, changeset: changeset, time: time)
  end

  def diff_time(timeblock) do
    start_time =  Integer.floor_div(timeblock.start_time, 1000)
    end_time =  Integer.floor_div(timeblock.end_time, 1000)
    Integer.floor_div((end_time - start_time), 60)
  end

end

lib/task2_web/views/task_view.ex
defmodule Task2Web.TaskView do
  use Task2Web, :view
end

lib/task2_web/templates/task/complete.html.eex
<script type="text/javascript">
  window.start_path = "<%= timeblock_path(@conn, :index) %>";
  window.task_id = "<%= @task.id %>"
</script>

<h2>Complete Task: <%= @task.title %></h2>
<p>Description: <%= @task.body %></p>
<div class="form-group">
  <label for="exampleInputEmail1">Input start Time (Your input must follow YYYY-MM-DDTHH:MM:SS, Like: 2018-01-01T03:24:00)</label>
  <input class="form-control" id="add-start-time">
</div>
<div class="form-group">
  <label for="exampleInputPassword1">Input End Time (Your input must follow YYYY-MM-DDTHH:MM:SS, Like: 2018-01-01T03:24:00)</label>
  <input class="form-control" id="add-end-time">
</div>
<div id="add-time-warnning"></div>
<button onclick="add_time_block()" class="btn btn-primary">Add Time Block</button>
<br/>

<button class="btn btn-primary"  id="start-button"
        data-start="false">
  Start Working
</button>
<h3>Work History(This uses Greenwich Mean Time)</h3>
<div id="edit-block"></div>
<div id="warnning"></div>
<table class="table">
  <thead>
    <tr>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Time Spent</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="blocks">
    <%= for timeblock <- @task.timeblocks do %>
      <tr id = "<%= "b"<>Integer.to_string(timeblock.id) %>" class="block-row">
        <% start_time =  Integer.floor_div(timeblock.start_time, 1000) %>
        <% end_time =  Integer.floor_div(timeblock.end_time, 1000) %>
        <% {:ok, start_iso} = DateTime.from_unix(start_time) %>
        <% {:ok, end_iso} = DateTime.from_unix(end_time) %>
        <th><%= start_iso %></th>
        <th><%= end_iso %></th>
        <th><%= Integer.floor_div((end_time - start_time), 60) %>minutes</th>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render "complete_form.html", Map.put(assigns, :action, task_path(@conn, :update, @task)) %>


<span><%= link "Back", to: task_path(@conn, :index) %></span>

lib/task2_web/templates/task/complete_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>


  <%= hidden_input f, :creater_id, value: @task.creater_id, class: "form-control" %>
  <%= hidden_input f, :title, value: @task.title, class: "form-control" %>
  <%= hidden_input f, :body, value: @task.body, class: "form-control" %>
  <%= hidden_input f, :user_id, value: @task.user_id, class: "form-control" %>
  <%= hidden_input f, :time, value: @time, class: "form-control" %>

  <div class="form-group">
    <%= submit "Complete Task", class: "btn btn-success" %>
  </div>

<% end %>

lib/task2_web/templates/task/edit.html.eex
<h2>Edit Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: task_path(@conn, :index) %></span>

lib/task2_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= if @current_user do %>
    <%= hidden_input f, :creater_id, value: @current_user.id, class: "form-control" %>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= label f, :assignee, class: "control-label" %>
    <%= select f, :user_id, @user_id_list, class: "form-control" %>
    <%= error_tag f, :user_id %>
  </div>

  <div class="form-group">
    <%= submit "Submit Task", class: "btn btn-primary" %>
  </div>
<% end %>

lib/task2_web/templates/task/index.html.eex
<h2>All Tasks</h2>
<table class="table">
  <thead>
    <tr>
      <th>Status</th>
      <th>Title</th>
      <th>Creater</th>
      <th>Assignee</th>
      <th>Time</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td id="status">
        <%= if task.time do %>
          Completed
        <% end %>
      </td>
      <td><%= task.title %></td>
      <td><%= task.creater.name %></td>
      <td>
        <%= if task.user_id == @current_user.id do %>
          <b id="notice"><%= task.user.name %></b>
        <% else %>
          <%= task.user.name %>
        <% end %>
      </td>
      <td>
      <%= if task.time do %>
        <span><%= task.time %></span><span> minutes</span>
      <% else %>
      <% end %>
      </td>

      <td class="text-right">
        <%= if @current_user.id == task.user_id do %>
          <span><%= link "Complete", to: task_complete_path(@conn, :complete, task), class: "btn btn-default btn-xs" %></span>
        <% end %>
        <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <%= if @current_user.id == task.creater_id do %>
        <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Task", to: task_path(@conn, :new) %></span>

lib/task2_web/templates/task/new.html.eex
<h2>New Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>

<span><%= link "Back", to: task_path(@conn, :index) %></span>

lib/task2_web/templates/task/show.html.eex
<h2>Show Task</h2>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @task.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @task.body %>
  </li>

  <li>
    <strong>Creater:</strong>
    <%= @task.creater.name %>
  </li>

  <li>
    <strong>Assignee:</strong>
    <%= @task.user.name %>
  </li>

  <li>
    <strong>Time:</strong>
    <%= @task.time %>
  </li>


</ul>

<%= if @current_user.id == @task.creater_id do %>
  <div><%= link "Edit", to: task_path(@conn, :edit, @task) %></div>
<% end %>
<div><%= link "Back", to: task_path(@conn, :index) %></div>